services:
  streamkey-hub:
    image: streamkey-hub
    build:
      context: .
      dockerfile: StreamKey.Hub/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:${HUB_PORT}
      - DOTNET_GCServer:1
      - DOTNET_EnableDiagnostics:0
      - DOTNET_SYSTEM_NET_SOCKETS_THREAD_COUNT=16
      - ASPNETCORE_THREADPOOL_MINTHREADS=200
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    env_file:
      - .env
    ports:
      - "${HUB_PORT}:${HUB_PORT}"
    volumes:
      - aspnet-keys:/root/.aspnet/DataProtection-Keys

volumes:
  aspnet-keys: