receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 128
    spike_limit_mib: 32
  batch:
    send_batch_size: 8192
    timeout: 5s

exporters:
  otlp/seq_traces:
    endpoint: http://seq:4319
    headers:
      X-Seq-ApiKey: ${SEQ_API_KEY}
    tls:
      insecure: true
  
  otlp/seq_metrics:
    endpoint: http://seq:4319
    headers:
      X-Seq-ApiKey: ${SEQ_API_KEY}
    tls:
      insecure: true
  
  otlp/seq_logs:
    endpoint: http://seq:4319
    headers:
      X-Seq-ApiKey: ${SEQ_API_KEY}
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "info"

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/seq_traces, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/seq_metrics, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/seq_logs, debug]
